word = "Bonjour World!"
print(word)
print(“Bonjour World!”)
print(“word”)
print(word[0])
print(len(word))
print(word.count("o"))
print(word.find("j"))
print(word.index("World"))
print(word.upper())
print(word.lower())
print(word.title())
print(word.capitalize())
print(word.swapcase())
print(print(word + “ Fromage!”))
print(print("hello " * 5))
print(print ''.join(reversed(word)))
print(print " ".join(word))
print(word.replace("World", "Pizza"))
print(word[8:16])
print(word[0:7])

